name: "Composite action to checkstyle"
description: "A composite action to run Checkstyle analysis"

inputs:
  skip-tests:
    description: "skip tests"
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: List directory
      run: ls
    - name: Build with Maven
      run: mvn checkstyle:checkstyle  
