name: Build Java app

on:
  push:
    branches:
      - main

jobs:
  checkout-build-upload:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: demo/demo    
      uses:
        working-directory: demo/demo            
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4
      - name: setup java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Build with Maven
        run: mvn clean package
      - name: List target directory
        run: ls target
      - name: upload artifact  
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: target/*.jar